### ISSUE TITLE
Delete Coffee feedback

### ISSUE THREAD

**Issue by Dujota** [bearcodes870/beanbino#1]
https://github.com/bearcodes870/beanbino/blob/430967160a95b4c48490d54f3d6cdd42a60f11d6/src/pages/CoffeeDetailPage/CoffeeDetailPage.jsx#L19

if you are deleting, you dont need to setState because if you delete the coffee, then there's no detail page for that coffee right? 

- so you should change the window location to  coffees/ (index)
- your coffee index page will get the list of coffees from the server and it will not include the coffee you just deleted

```
 handleDeleteCoffee = (coffee<---- this paramenter should be called id ) => {
      this.setState({coffee}); <--- get rid of this
     // here you need to use the coffeeService instead
    coffeeService.delete(id)
  }
  ```

**Comment by bearcodes870** [comment]
Hey @Dujota thanks for looking at my repo and for the tips -

I tried this fix (removed this.SetState, and implemented window.location) to be able to delete the coffee and reroute back to the index page.

Index page rendered but it still has the "old" coffee in the list at the same position.

**Comment by Dujota** [comment]
@bearcodes870 make small changes commit and push them up so we can debug your code as it evolves

having said that, you need to call the coffeeService.delete(id) before you change location

think of the steps: 
1- delete the coffee from the db
2  - once the delete is completed you can change the windows url to the index
